-- Füge die neuen Spalten zur 'settings' Tabelle hinzu
ALTER TABLE settings 
ADD COLUMN IF NOT EXISTS savings_balance numeric DEFAULT 0,
ADD COLUMN IF NOT EXISTS savings_months_remaining integer DEFAULT 0,
ADD COLUMN IF NOT EXISTS last_processed_month text;

-- Optional: Setze den aktuellen Monat als Startwert für existierende Einträge
UPDATE settings 
SET last_processed_month = TO_CHAR(NOW(), 'YYYY-MM') 
WHERE last_processed_month IS NULL;

-- Erstelle die 'accounts' Tabelle für das neue Feature
CREATE TABLE IF NOT EXISTS accounts (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  amount numeric not null,
  months integer not null,
  processed_month text
);
